### ISSUE TITLE
compile and opengl issue on ubuntu 16.04

### ISSUE THREAD

**Issue by toastbrotch** [bigfug/Fugio#14]
i followed instructions on wiki how to compile. seems paket libglew-dev is also needed.
ubuntu16.04 installs 1.13.0 of it. compilation runs thru then. 

in fugio with shader examples loaded: all GL nodes are red and from logger:

```
/home/ivo/Downloads/Fugio/deploy-release-x86_64/plugins/libfugio-opengl.so" : "Cannot load library /home/ivo/Downloads/Fugio/deploy-release-x86_64/plugins/libfugio-opengl.so: (/home/ivo/Downloads/Fugio/deploy-release-x86_64/plugins/libfugio-opengl.so: undefined symbol: __glewFramebufferTexture3D)
```

some more information:

```
glewinfo|grep FramebufferTexture3D
  glFramebufferTexture3D:                                      OK
  glNamedFramebufferTexture3DEXT:                              MISSING
  glFramebufferTexture3DEXT:                                   OK

dpkg -l|grep glew|awk '{print " ",$2,"\t",$3}'
  glew-utils     1.13.0-2
  libglew-dev:amd64      1.13.0-2
  libglew1.13:amd64      1.13.0-2
  libglewmx1.13:amd64    1.13.0-2

```

**Comment by toastbrotch** [comment]
still with fugio 1.8

**Comment by bigfug** [comment]
Old issue that I'm assuming is fixed (let me know if it isn't!)

**Comment by toastbrotch** [comment]
i still see this with current code and ubuntu17.04 setup as posted on https://www.facebook.com/groups/fugio/permalink/1898527857084535/ ... but maybe i miss a library or something (on non-nvidia graficcard)
